load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "Test_Propylean",
    srcs = ["propylean.cc"],
    deps = [
        "//lib:The_Ledger_Co",
        "@com_google_googletest//:gtest_main",
    ],
)